-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        ["PerkData"] = {
            ["DoubleWages"] = true,
            ["SlowMoodDecline"] = true,
            ["StreetRacer"] = true
        },
        ["SettingsData"] = {
            ["ShowServerFPS"] = false,
            ["CustomTextures"] = true,
            ["ShowCharName"] = true,
            ["FriendsCanEmote"] = true,
            ["ShowNameplate"] = true,
            ["TradeRequests"] = true,
            ["NameSpecialColor"] = false,
            ["DepositTimer"] = true,
            ["WorldParticles"] = true,
            ["ShowAllNameplates"] = true,
            ["GameMusic"] = false,
            ["HideHotkeys"] = false,
            ["CopyrightedSounds"] = false,
            ["HideMinimap"] = false,
            ["PropShadows"] = true,
            ["DisruptiveSounds"] = false,
            ["HideMyMarker"] = false,
            ["ShowFPS"] = false
        },
        ["InvestmentData"] = {
            ["Investment2"] = 1514237346,
            ["Investment1"] = 1514237347,
            ["Investment3"] = 1514237345,
            ["Investment4"] = 1514237344
        },
        ["ProductData"] = {
            ["Starter Pack"] = 0
        },
        ["JobData"] = {
            ["TotalWorkTime"] = 2048
        },
        ["CareerData"] = {
            ["Medicine"] = 1000,
            ["Retail"] = 1000,
            ["Law Enforcement"] = 0,
            ["Crime"] = 671,
            ["Driving"] = 0,
            ["Cuisine"] = 26
        },
        ["BoatData"] = {
            [1] = {
                ["TertiaryColor"] = "Burlap",
                ["Price"] = 11500000,
                ["Frame"] = "Hurricane",
                ["PrimaryColor"] = "Medium blue",
                ["SecondaryColor"] = "Medium stone grey"
            }
        },
        ["CurrencyData"] = {
            ["Candy"] = 0
        },
        ["CosmeticData2"] = {
            ["Owned"] = {
                ["Pants"] = {
                    [1] = 7825740,
                    [2] = 12786204,
                    [3] = 103841330,
                    [4] = 70612413,
                    [5] = 181079536,
                    [6] = 176874685,
                    [7] = 167422533,
                    [8] = 129459077,
                    [9] = 129458426,
                    [10] = 110006599,
                    [11] = 134892057,
                    [12] = 89179059,
                    [13] = 165988675,
                    [14] = 37786062,
                    [15] = 166969249,
                    [16] = 295144283,
                    [17] = 234208227,
                    [18] = 291167623,
                    [19] = 236078936,
                    [20] = 180167515,
                    [21] = 223196650,
                    [22] = 224949399,
                    [23] = 237997088,
                    [24] = 117208913,
                    [25] = 76314558,
                    [26] = 242626649,
                    [27] = 180644836,
                    [28] = 242843373,
                    [29] = 302265795,
                    [30] = 274489565,
                    [31] = 241941892,
                    [32] = 181090067,
                    [33] = 275592666,
                    [34] = 229804187,
                    [35] = 206784443,
                    [36] = 104446238,
                    [37] = 249020050,
                    [38] = 329766144,
                    [39] = 232870597,
                    [40] = 189743105,
                    [41] = 326329739,
                    [42] = 327736041,
                    [43] = 325032045,
                    [44] = 194017267,
                    [45] = 327192580,
                    [46] = 326042259,
                    [47] = 325002979,
                    [48] = 191725620,
                    [49] = 278825978,
                    [50] = 329981118,
                    [51] = 163091723,
                    [52] = 232385821,
                    [53] = 363803257,
                    [54] = 149117245,
                    [55] = 233060285,
                    [56] = 233110712,
                    [57] = 234057160,
                    [58] = 238867711,
                    [59] = 75501242,
                    [60] = 243290965,
                    [61] = 231598614,
                    [62] = 241424819,
                    [63] = 237906953,
                    [64] = 370558518,
                    [65] = 109084273,
                    [66] = 375745022,
                    [67] = 224406766,
                    [68] = 230503687,
                    [69] = 549206893,
                    [70] = 274017261,
                    [71] = 74969171,
                    [72] = 223149549,
                    [73] = 363145024,
                    [74] = 220919091,
                    [75] = 225128357,
                    [76] = 344710810,
                    [77] = 296721472,
                    [78] = 108784532,
                    [79] = 2089569391,
                    [80] = 166203022,
                    [81] = 221305609,
                    [82] = 159445322,
                    [83] = 402672675,
                    [84] = 237660135,
                    [85] = 393127193,
                    [86] = 148626406,
                    [87] = 153305263,
                    [88] = 268765041,
                    [89] = 398901252,
                    [90] = 121092420,
                    [91] = 237747079,
                    [92] = 199673296,
                    [93] = 389723245,
                    [94] = 178608222,
                    [95] = 348802465,
                    [96] = 269564102,
                    [97] = 159744084,
                    [98] = 385382479,
                    [99] = 113011466,
                    [100] = 186027861,
                    [101] = 408311999,
                    [102] = 78562267,
                    [103] = 408311003,
                    [104] = 108784536,
                    [105] = 335127778,
                    [106] = 272177052,
                    [107] = 247348351,
                    [108] = 409502402,
                    [109] = 224839559,
                    [110] = 263606744,
                    [111] = 404981417,
                    [112] = 236121993,
                    [113] = 78562346,
                    [114] = 429116594,
                    [115] = 268981319,
                    [116] = 313571625,
                    [117] = 480512336,
                    [118] = 221256393,
                    [119] = 193751267,
                    [120] = 298065200,
                    [121] = 518515339,
                    [122] = 238231088,
                    [123] = 472798944,
                    [124] = 316106385,
                    [125] = 222387205,
                    [126] = 472761039,
                    [127] = 274063363,
                    [128] = 234781448,
                    [129] = 522481250,
                    [130] = 517545701,
                    [131] = 521369741,
                    [132] = 333962036,
                    [133] = 336062674,
                    [134] = 564532384,
                    [135] = 324807883,
                    [136] = 337650040,
                    [137] = 247016311,
                    [138] = 148446334,
                    [139] = 223048199,
                    [140] = 241313938,
                    [141] = 1038398393,
                    [142] = 825118346,
                    [143] = 203939353,
                    [144] = 313888724,
                    [145] = 1088676043,
                    [146] = 1121920031,
                    [147] = 1040013609,
                    [148] = 64231074,
                    [149] = 1103467667,
                    [150] = 1106360939,
                    [151] = 1091653113,
                    [152] = 1088757364,
                    [153] = 203470466,
                    [154] = 425601357,
                    [155] = 188338077,
                    [156] = 758941110,
                    [157] = 546300781,
                    [158] = 805994893,
                    [159] = 184025203,
                    [160] = 1236128923,
                    [161] = 1240308995,
                    [162] = 783710813,
                    [163] = 1167957347,
                    [164] = 1242001518,
                    [165] = 1228700774,
                    [166] = 1209985387,
                    [167] = 1036571366,
                    [168] = 563134037,
                    [169] = 1213683470,
                    [170] = 336059102,
                    [171] = 556376285,
                    [172] = 1234143494,
                    [173] = 791195224
                },
                ["Hat"] = {
                    [1] = 1563352,
                    [2] = 1235488,
                    [3] = 19027209,
                    [4] = 10476359,
                    [5] = 16412796,
                    [6] = 1285307,
                    [7] = 0,
                    [8] = 17903982,
                    [9] = 1374258,
                    [10] = 17450053,
                    [11] = 163497528,
                    [12] = 8798578,
                    [13] = 0,
                    [14] = 0,
                    [15] = 0,
                    [16] = 1043468,
                    [17] = 12730033,
                    [18] = 139152149,
                    [19] = 1374269,
                    [20] = 1165248,
                    [21] = 1081300,
                    [22] = 53040003,
                    [23] = 20642008,
                    [24] = 1235487,
                    [25] = 1098277,
                    [26] = 42801967,
                    [27] = 143629585,
                    [28] = 0,
                    [29] = 63689493,
                    [30] = 0,
                    [31] = 139152387,
                    [32] = 66747278,
                    [33] = 230716441,
                    [34] = 154415191,
                    [35] = 23962538,
                    [36] = 150337770,
                    [37] = 228449468,
                    [38] = 0
                },
                ["Shirt"] = {
                    [1] = 294224276,
                    [2] = 74917914,
                    [3] = 128409830,
                    [4] = 772771146,
                    [5] = 1221390683,
                    [6] = 190975443,
                    [7] = 214175318,
                    [8] = 302600285,
                    [9] = 25173493,
                    [10] = 10668532,
                    [11] = 147222550,
                    [12] = 727421259,
                    [13] = 130680477,
                    [14] = 239588139,
                    [15] = 515524658,
                    [16] = 223866940,
                    [17] = 223323984,
                    [18] = 402812506,
                    [19] = 239608177,
                    [20] = 233608794,
                    [21] = 1210341183,
                    [22] = 237052983,
                    [23] = 304967225,
                    [24] = 235880654,
                    [25] = 186571853,
                    [26] = 109382021,
                    [27] = 145492365,
                    [28] = 229987681,
                    [29] = 368799850,
                    [30] = 235493547,
                    [31] = 362989839,
                    [32] = 234711977,
                    [33] = 177716272,
                    [34] = 194523693,
                    [35] = 549850149,
                    [36] = 239886611,
                    [37] = 522575026,
                    [38] = 582739963,
                    [39] = 218401588,
                    [40] = 762581573,
                    [41] = 227839545,
                    [42] = 377863368,
                    [43] = 108976231,
                    [44] = 166969226,
                    [45] = 152185080,
                    [46] = 328750385,
                    [47] = 767371921,
                    [48] = 1222940335,
                    [49] = 13343843,
                    [50] = 109290907,
                    [51] = 109300072,
                    [52] = 116813204,
                    [53] = 593753601,
                    [54] = 335280351,
                    [55] = 327859470,
                    [56] = 13997653,
                    [57] = 575732309,
                    [58] = 78535191,
                    [59] = 108129063,
                    [60] = 176874519,
                    [61] = 65615574,
                    [62] = 75019582,
                    [63] = 222749660,
                    [64] = 114383655,
                    [65] = 1210362034,
                    [66] = 224924719,
                    [67] = 382537085,
                    [68] = 252697964,
                    [69] = 115435587,
                    [70] = 188587775,
                    [71] = 31614252,
                    [72] = 191688492,
                    [73] = 108159019,
                    [74] = 516027655,
                    [75] = 104446027,
                    [76] = 232902087,
                    [77] = 1106204603,
                    [78] = 109405739,
                    [79] = 1235267376,
                    [80] = 1240527438,
                    [81] = 1229702256,
                    [82] = 368799850,
                    [83] = 152901159,
                    [84] = 234610617,
                    [85] = 241542227,
                    [86] = 241542227,
                    [87] = 1063863813,
                    [88] = 179651766,
                    [89] = 124021923,
                    [90] = 167405454,
                    [91] = 229829050,
                    [92] = 230328797,
                    [93] = 188629949,
                    [94] = 594619094,
                    [95] = 234818231,
                    [96] = 23520117,
                    [97] = 295480176,
                    [98] = 8378915,
                    [99] = 252309905,
                    [100] = 651119936,
                    [101] = 219806506,
                    [102] = 206187066,
                    [103] = 262913193,
                    [104] = 256823994,
                    [105] = 117208903,
                    [106] = 134046739,
                    [107] = 98840319,
                    [108] = 1011546913,
                    [109] = 199934871,
                    [110] = 1042817045,
                    [111] = 517653399,
                    [112] = 228750026,
                    [113] = 180801632,
                    [114] = 233283934,
                    [115] = 1103488120,
                    [116] = 176077543,
                    [117] = 807285334,
                    [118] = 220023353,
                    [119] = 141870326,
                    [120] = 8445430,
                    [121] = 1086395246,
                    [122] = 167405454,
                    [123] = 1179314561,
                    [124] = 333833625,
                    [125] = 1179643380,
                    [126] = 278220886,
                    [127] = 319957967,
                    [128] = 1077223141,
                    [129] = 1241746125,
                    [130] = 172478178,
                    [131] = 145980237,
                    [132] = 226706594,
                    [133] = 115435596,
                    [134] = 88128885,
                    [135] = 137087817,
                    [136] = 109385308,
                    [137] = 6553199,
                    [138] = 284594626,
                    [139] = 190929299,
                    [140] = 241575269,
                    [141] = 169086892,
                    [142] = 263330994,
                    [143] = 1218186038,
                    [144] = 190882944,
                    [145] = 561555800,
                    [146] = 193751221,
                    [147] = 207828785,
                    [148] = 714980007,
                    [149] = 588584339,
                    [150] = 758648271,
                    [151] = 747880587,
                    [152] = 231374321,
                    [153] = 114394041,
                    [154] = 109563106,
                    [155] = 151080756,
                    [156] = 151080802,
                    [157] = 105811957,
                    [158] = 236078859,
                    [159] = 230377351,
                    [160] = 62300691,
                    [161] = 152926981,
                    [162] = 1057902864,
                    [163] = 109382012,
                    [164] = 109290891,
                    [165] = 109300070,
                    [166] = 182269820,
                    [167] = 227319525,
                    [168] = 450264311,
                    [169] = 200773887,
                    [170] = 209180960,
                    [171] = 329204527,
                    [172] = 593993058,
                    [173] = 318904243,
                    [174] = 1114543968,
                    [175] = 150018094,
                    [176] = 230366778,
                    [177] = 488600470,
                    [178] = 183615712,
                    [179] = 728564800,
                    [180] = 206752709,
                    [181] = 13997675,
                    [182] = 115435598,
                    [183] = 65380689,
                    [184] = 90415298,
                    [185] = 190453649,
                    [186] = 273504575,
                    [187] = 282420441,
                    [188] = 222730608,
                    [189] = 293378385,
                    [190] = 137040211,
                    [191] = 65387141,
                    [192] = 41173533,
                    [193] = 6658208,
                    [194] = 65468015,
                    [195] = 285175151,
                    [196] = 593957189,
                    [197] = 1234100481,
                    [198] = 230197245,
                    [199] = 303117686,
                    [200] = 275592386,
                    [201] = 271701077,
                    [202] = 955965619,
                    [203] = 152628827
                },
                ["Hair"] = {
                    [1] = 80921949,
                    [2] = 41852455,
                    [3] = 62678172,
                    [4] = 175136000,
                    [5] = 295456068,
                    [6] = 13745548,
                    [7] = 63688835,
                    [8] = 16157972,
                    [9] = 32278814,
                    [10] = 14129164,
                    [11] = 186957762,
                    [12] = 26658141,
                    [13] = 20573078,
                    [14] = 16630147,
                    [15] = 293316132,
                    [16] = 62745990,
                    [17] = 80922251,
                    [18] = 1708329071,
                    [19] = 376548598
                }
            },
            ["CurrentOutfit"] = 3,
            ["Outfits"] = {
                [1] = {
                    ["Face1"] = {
                        ["Id"] = "31117267"
                    },
                    ["SkinColor"] = {
                        ["Color"] = {
                            [1] = 0.8,
                            [2] = 0.56,
                            [3] = 0.41
                        }
                    },
                    ["CharacterName"] = {
                        ["Value"] = "Josh"
                    },
                    ["Hair2"] = {
                        ["Id"] = 16630147,
                        ["Tuning"] = {
                            ["Color"] = {
                                [1] = 0,
                                [2] = 1,
                                [3] = 1
                            }
                        },
                        ["TextureOn"] = false
                    },
                    ["Shirt1"] = {
                        ["Id"] = 62300691
                    },
                    ["Face"] = {
                        ["Id"] = 144075659
                    },
                    ["Age"] = {
                        ["Value"] = 17
                    },
                    ["Pants1"] = {
                        ["Id"] = 224406766
                    }
                },
                [2] = {
                    ["CharacterName"] = {
                        ["Value"] = "........"
                    },
                    ["SkinColor"] = {
                        ["Color"] = {
                            [1] = 0.8,
                            [2] = 0.56,
                            [3] = 0.41
                        }
                    },
                    ["Pants1"] = {
                        ["Id"] = 269564102
                    },
                    ["Shirt1"] = {
                        ["Id"] = 108129063
                    },
                    ["Face"] = {
                        ["Id"] = 144075659
                    },
                    ["Age"] = {
                        ["Value"] = 18
                    },
                    ["Hair2"] = {
                        ["Id"] = 16630147,
                        ["Tuning"] = {
                            ["Color"] = {
                                [1] = 1,
                                [2] = 0,
                                [3] = 0
                            }
                        },
                        ["TextureOn"] = false
                    }
                },
                [3] = {
                    ["Hat3"] = {
                        ["Id"] = 1165248
                    },
                    ["Pants1"] = {
                        ["Id"] = 224406766
                    },
                    ["Face"] = {
                        ["Id"] = 144075659
                    },
                    ["Age"] = {
                        ["Value"] = 17
                    },
                    ["CharacterName"] = {
                        ["Value"] = "Josh"
                    },
                    ["Hair2"] = {
                        ["Id"] = 16630147,
                        ["Tuning"] = {
                            ["Color"] = {
                                [1] = 0.16357824941418,
                                [2] = 0.40923630221371,
                                [3] = 0.46179386549579
                            }
                        },
                        ["TextureOn"] = false
                    },
                    ["Shirt1"] = {
                        ["Id"] = 62300691
                    },
                    ["OutfitName"] = "Outfit 3",
                    ["SkinColor"] = {
                        ["Color"] = {
                            [1] = 0.8,
                            [2] = 0.56,
                            [3] = 0.41
                        }
                    },
                    ["Face1"] = {
                        ["Id"] = "31117267"
                    }
                }
            }
        },
        ["ExperienceData"] = {
            ["SkillsData"] = {
                ["Cooking"] = {
                    ["Rewards"] = {
                        [1] = "Kebabs",
                        [2] = "Grilled Steak",
                        [3] = "S'Mores",
                        [4] = "Hamburgers",
                        [5] = "Grilled Chicken",
                        [6] = "Grilled Cheese",
                        [7] = "Sushi",
                        [8] = "Lasagna",
                        [9] = "Gravy",
                        [10] = "Nachos",
                        [11] = "Cooked Turkey",
                        [12] = "Chocolate Chip Cookies",
                        [13] = "Pecan Pie",
                        [14] = "Tamales",
                        [15] = "Gingerbread Cookie",
                        [16] = "Apple Pie",
                        [17] = "Baked Potatoes",
                        [18] = "Pizza",
                        [19] = "Stuffing",
                        [20] = "Christmas Cookie",
                        [21] = "Eggnog",
                        [22] = "Scrambled Eggs",
                        [23] = "Latke",
                        [24] = "French Toast",
                        [25] = "Pancakes",
                        [26] = "Chocolate Cake",
                        [27] = "Hot Cocoa",
                        [28] = "Mashed Potatoes",
                        [29] = "Grilled Cheese",
                        [30] = "Fried Bacon",
                        [31] = "Pumpkin Pie",
                        [32] = "Mac N' Cheese",
                        [33] = "Fried Eggs"
                    },
                    ["Level"] = 0,
                    ["Experience"] = 0,
                    ["Required"] = 60
                }
            }
        },
        ["EventData"] = {
            ["Imagination"] = {
                ["FurnitureData"] = "",
                ["RoomColorData"] = ""
            }
        },
        ["MusicData"] = {
            ["Songs"] = {},
            ["Playlists"] = {}
        },
        ["SingularData"] = {
            ["PreviousDay"] = 18965,
            ["Palms Standard"] = true,
            ["SerialIndex"] = 22,
            ["Streak"] = 0,
            ["Exploiter"] = true,
            ["Moderation"] = {
                [1] = {
                    ["Infraction"] = "Client-modified currency (candy)",
                    ["Penalty"] = {
                        [1] = "Set Candy to -99900000",
                        [2] = "Removed blueprint: Haunted Manor"
                    }
                }
            }
        },
        ["QuestData"] = {
            ["Completed"] = {
                [1] = 1,
                [2] = 3,
                [3] = 2,
                [4] = 20
            },
            ["Current"] = {}
        },
        ["InventoryData"] = {
            ["Blueprints"] = {
                [1] = "Small Cabin",
                [2] = "Antine Villa",
                [3] = "Taylorian",
                [4] = "Modern Bungalow",
                [5] = "Contemporarian",
                [6] = "Craftsman",
                [7] = "Classic Mansion",
                [8] = "Classic Suburban",
                [9] = "Luxury Cabin"
            },
            ["Furniture"] = {
                [1] = {
                    ["Color"] = "White",
                    ["Serial"] = 22,
                    ["Name"] = "Agrarian Architecture Stove Vent"
                },
                [2] = {
                    ["Color"] = "White",
                    ["Serial"] = 21,
                    ["Name"] = "Agrarian Architecture Stove Vent"
                },
                [3] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 93,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [4] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 91,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [5] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 89,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [6] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 88,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [7] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 87,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [8] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 86,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [9] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 85,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [10] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 84,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [11] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 83,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [12] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 82,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [13] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 81,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [14] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 80,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [15] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 79,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [16] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 78,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [17] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 77,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [18] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 76,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [19] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 75,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [20] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 74,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [21] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 73,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [22] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 72,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [23] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 71,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [24] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 70,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [25] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 69,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [26] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 68,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [27] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 67,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [28] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 66,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [29] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 65,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [30] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 64,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [31] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 63,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [32] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 62,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [33] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 61,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [34] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 60,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [35] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 59,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [36] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 58,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [37] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 57,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [38] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 55,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [39] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 54,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [40] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 53,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [41] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 52,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [42] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 51,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [43] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 50,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [44] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 49,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [45] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 48,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [46] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 47,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [47] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 46,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [48] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 45,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [49] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 44,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [50] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 43,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [51] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 42,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [52] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 41,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [53] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 40,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [54] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 39,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [55] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 38,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [56] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 37,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [57] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 34,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [58] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 33,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [59] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 31,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [60] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 30,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [61] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 29,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [62] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 28,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [63] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 26,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [64] = {
                    ["Color"] = "Maroon",
                    ["Serial"] = 25,
                    ["Name"] = "ConstrucTON Half Counter"
                },
                [65] = {
                    ["Color"] = "White",
                    ["Serial"] = 1,
                    ["Name"] = "Kagu Imports Coffee Table"
                },
                [66] = {
                    ["Color"] = "Cocoa",
                    ["Serial"] = 2,
                    ["Name"] = "Kagu Imports Table"
                },
                [67] = {
                    ["Color"] = "Really black",
                    ["Serial"] = 3,
                    ["Name"] = "Sovereignty Laptop"
                },
                [68] = {
                    ["Color"] = "Reddish brown",
                    ["Serial"] = 4,
                    ["Name"] = "Double Bubble Hot Tub"
                },
                [69] = {
                    ["Color"] = "White",
                    ["Serial"] = 5,
                    ["Name"] = "Glub Tub Bathtub"
                },
                [70] = {
                    ["Color"] = "Sand blue",
                    ["Serial"] = 6,
                    ["Name"] = "Slo Drip Shower"
                },
                [71] = {
                    ["Color2"] = "Black metallic",
                    ["Name"] = "Corny Sunset",
                    ["Display"] = "Framed",
                    ["Serial"] = 7,
                    ["Color1"] = "Black metallic"
                },
                [72] = {
                    ["Color"] = "Reddish brown",
                    ["Serial"] = 8,
                    ["Name"] = "Dust Catcher Bookshelf"
                },
                [73] = {
                    ["Color"] = "Dark stone grey",
                    ["Serial"] = 9,
                    ["Name"] = "Fire Brand Modern Fireplace"
                },
                [74] = {
                    ["Color"] = "Earth green",
                    ["Serial"] = 10,
                    ["Name"] = "Holly Cow Christmas Tree"
                },
                [75] = {
                    ["Color"] = "White",
                    ["Serial"] = 11,
                    ["Name"] = "Kagu Imports Banner"
                },
                [76] = {
                    ["Color"] = "Really black",
                    ["Serial"] = 12,
                    ["Name"] = "Kagu Imports Sword Display"
                },
                [77] = {
                    ["Color2"] = "Brown",
                    ["Name"] = "Portrait of a Young Woman",
                    ["Display"] = "Framed",
                    ["Serial"] = 15,
                    ["Color1"] = "Reddish brown"
                },
                [78] = {
                    ["Color2"] = "Brown",
                    ["Name"] = "Portrait of a Young Woman",
                    ["Display"] = "Framed",
                    ["Serial"] = 16,
                    ["Color1"] = "Light orange brown"
                },
                [79] = {
                    ["Color2"] = "Brown",
                    ["Name"] = "Portrait of a Young Woman",
                    ["Display"] = "Framed",
                    ["Serial"] = 13,
                    ["Color1"] = "Reddish brown"
                },
                [80] = {
                    ["Color2"] = "Brown",
                    ["Name"] = "Portrait of a Young Woman",
                    ["Display"] = "Framed",
                    ["Serial"] = 18,
                    ["Color1"] = "Reddish brown"
                },
                [81] = {
                    ["Color2"] = "Brown",
                    ["Name"] = "Portrait of a Young Woman",
                    ["Display"] = "Framed",
                    ["Serial"] = 17,
                    ["Color1"] = "Dark orange"
                },
                [82] = {
                    ["Color2"] = "Brown",
                    ["Name"] = "Portrait of a Young Woman",
                    ["Display"] = "Framed",
                    ["Serial"] = 14,
                    ["Color1"] = "Reddish brown"
                },
                [83] = {
                    ["Color2"] = "Brown",
                    ["Name"] = "Portrait of a Young Woman",
                    ["Display"] = "Framed",
                    ["Serial"] = 19,
                    ["Color1"] = "Reddish brown"
                },
                [84] = {
                    ["Color"] = "Bright green",
                    ["Serial"] = 20,
                    ["Name"] = "Solid Stripes Pool Table"
                }
            },
            ["Food"] = {
                [1] = {
                    ["Name"] = "Lasagna",
                    ["Amount"] = 1
                },
                [2] = {
                    ["Name"] = "Chocolate Chip Cookie",
                    ["Amount"] = 1
                },
                [3] = {
                    ["Name"] = "Chocolate Ice Cream Cone",
                    ["Amount"] = 2
                },
                [4] = {
                    ["Name"] = "Candy",
                    ["Amount"] = 189
                },
                [5] = {
                    ["Name"] = "Chocolate Bar",
                    ["Amount"] = 23
                },
                [6] = {
                    ["Name"] = "Yogurt",
                    ["Amount"] = 4
                },
                [7] = {
                    ["Name"] = "Apple",
                    ["Amount"] = 4
                },
                [8] = {
                    ["Name"] = "Bell Pepper",
                    ["Amount"] = 10
                },
                [9] = {
                    ["Name"] = "Pineapple",
                    ["Amount"] = 5
                },
                [10] = {
                    ["Name"] = "Pumpkin",
                    ["Amount"] = 6
                },
                [11] = {
                    ["Name"] = "Ground Beef",
                    ["Amount"] = 8
                },
                [12] = {
                    ["Name"] = "Hamburger Patties",
                    ["Amount"] = 10
                },
                [13] = {
                    ["Name"] = "Steak",
                    ["Amount"] = 8
                },
                [14] = {
                    ["Name"] = "Turkey",
                    ["Amount"] = 28
                },
                [15] = {
                    ["Name"] = "Butter",
                    ["Amount"] = 31
                },
                [16] = {
                    ["Name"] = "Cheese Block",
                    ["Amount"] = 16
                },
                [17] = {
                    ["Name"] = "Eggs",
                    ["Amount"] = 4
                },
                [18] = {
                    ["Name"] = "Milk",
                    ["Amount"] = 4
                },
                [19] = {
                    ["Name"] = "Bag of Flour",
                    ["Amount"] = 5
                },
                [20] = {
                    ["Name"] = "Bag of Sugar",
                    ["Amount"] = 16
                },
                [21] = {
                    ["Name"] = "Bread",
                    ["Amount"] = 9
                },
                [22] = {
                    ["Name"] = "Hamburger Buns",
                    ["Amount"] = 10
                },
                [23] = {
                    ["Name"] = "Lasagna Noodles",
                    ["Amount"] = 11
                },
                [24] = {
                    ["Name"] = "Macaroni Noodles",
                    ["Amount"] = 49
                },
                [25] = {
                    ["Name"] = "Pumpkin Spice",
                    ["Amount"] = 10
                },
                [26] = {
                    ["Name"] = "Seasoning",
                    ["Amount"] = 9
                },
                [27] = {
                    ["Name"] = "Tomato Sauce",
                    ["Amount"] = 17
                }
            },
            ["Collectible"] = {},
            ["Leisure"] = {
                [1] = {
                    ["Name"] = "Wooden Dreidel",
                    ["Amount"] = 1
                },
                [2] = {
                    ["Name"] = "Hotdog Tube",
                    ["Amount"] = 1
                },
                [3] = {
                    ["Name"] = "Banana Boat",
                    ["Amount"] = 1
                },
                [4] = {
                    ["Name"] = "Pool Noodle",
                    ["Amount"] = 1
                },
                [5] = {
                    ["Name"] = "Inner Tube",
                    ["Amount"] = 1
                }
            }
        },
        ["AnalyticsData"] = {
            ["Veteran"] = 0,
            ["Session Number"] = 110,
            ["Transaction Number"] = 0,
            ["Total Time"] = 10977
        },
        ["CarData"] = {
            [1] = {
                ["Hood"] = "Standard",
                ["Spoiler"] = "None",
                ["SpoilerColor"] = "Lime green",
                ["SecondaryColor"] = "Really black",
                ["Rims"] = "5 Spoke",
                ["Skirts"] = "None",
                ["Price"] = 24400,
                ["PrimaryColor"] = "Really red",
                ["Frame"] = "Sleigher",
                ["SkirtsColor"] = "Really red",
                ["RimColor"] = "Lime green"
            },
            [2] = {
                ["Hood"] = "Standard",
                ["Spoiler"] = "None",
                ["SpoilerColor"] = "Mid gray",
                ["Price"] = 4400,
                ["Rims"] = "5 Spoke",
                ["IsActive"] = true,
                ["SkirtsColor"] = "Mid gray",
                ["PrimaryColor"] = "Medium blue",
                ["SecondaryColor"] = "Really black",
                ["Frame"] = "Sleigher",
                ["Skirts"] = "None",
                ["RimColor"] = "Medium stone grey"
            }
        },
        ["IndependentData"] = {
            ["Streak"] = 0,
            ["Outdoor2019"] = true,
            ["HanukkahUpdate2018"] = true,
            ["ShopJune2020"] = true,
            ["NotificationsSeen"] = {},
            ["PreviousDay"] = 18475,
            ["Comfort"] = 0,
            ["HalloweenUpdate2018"] = true,
            ["StudioIntroShown"] = true,
            ["October2016Event"] = true,
            ["Thanksgiving2021"] = true,
            ["Boats2021"] = true,
            ["CosmeticUpdate2018"] = true,
            ["Summer2020"] = true,
            ["Halloween2020"] = true,
            ["CarUpdate2020"] = true,
            ["PhoneWallpaper"] = "rbxassetid://248254225",
            ["December2017Event"] = true,
            ["Gender"] = "Male",
            ["October2017Event"] = true,
            ["Welcome"] = true,
            ["Fun"] = 0,
            ["Laundry2020"] = true,
            ["Hunger"] = 0,
            ["WallpaperCustom"] = false,
            ["Hygiene"] = 0,
            ["TourShown"] = true,
            ["Energy"] = 0,
            ["OctoberFurnitureRework2020"] = true
        },
        ["Version"] = 2,
        ["TradeData"] = {
            ["18544"] = {
                ["bbygirl957"] = {
                    ["Money"] = -4000,
                    ["ItemValue"] = 15
                }
            }
        },
        ["PreviewData"] = {
            ["Condo1"] = {
                ["Type"] = "Palms Standard",
                ["Count"] = 0,
                ["Value"] = 0,
                ["Length"] = 60,
                ["LastUpdated"] = 1638325505
            },
            ["House3"] = {
                ["Value"] = 100000,
                ["Type"] = "Haunted Manor",
                ["Length"] = 59
            },
            ["Apartment1"] = {
                ["Value"] = 0,
                ["Type"] = "Standard Mirror",
                ["Length"] = 61
            },
            ["House1"] = {
                ["Value"] = 275625,
                ["Type"] = "Antine Villa",
                ["Length"] = 12567
            },
            ["House2"] = {
                ["Value"] = 91060,
                ["Type"] = "Contemporarian",
                ["Length"] = 3600
            }
        },
        ["TrailerData"] = {},
        ["Money"] = 1,
        ["CosmeticData"] = {
            ["Clothing"] = {
                ["Christmas Pants"] = true,
                ["Palm Springs"] = true,
                ["Bald"] = true,
                ["Gingerbread Tee"] = true,
                ["Knitted Navy Blue"] = true,
                ["The Little Mermaid"] = true,
                ["Red Jeans"] = true,
                ["Pastel Hat"] = true,
                ["Ash Top"] = true,
                ["Navy Blue Stripes"] = true,
                ["Teal Bikini"] = true,
                ["Striped Shirt & Vest"] = true,
                ["Snow Cap"] = true,
                ["Deadpool"] = true,
                ["Chibi Snowman"] = true,
                ["Snowman PJs"] = true,
                ["Blue Jacket"] = true,
                ["Giftwrap Dress"] = true,
                ["Joker Jacket"] = true,
                ["I Am One With The Egg"] = true,
                ["Kirito Top"] = true,
                ["Elf Uniform"] = true,
                ["Orange Flannel"] = true,
                ["Christmas Sweater"] = true,
                ["Shiro"] = true,
                ["Swegg"] = true,
                ["Green Striped Tank"] = true,
                ["Swag Rudolph"] = true,
                ["Link Hat"] = true,
                ["Knit Stripes"] = true,
                ["Timeless Spring Top"] = true,
                ["Easter Hoodie"] = true,
                ["Reindeer Sweater"] = true,
                ["Green Elf Hat"] = true,
                ["Light Wash Jeans"] = true,
                ["Love Pink Sweater"] = true,
                ["Egg Man"] = true,
                ["Christmas Deluxe"] = true,
                ["Pizza"] = true,
                ["Beautiful"] = true,
                ["Penguins"] = true,
                ["Dragon Tee"] = true,
                ["Witch Hat"] = true,
                ["Captain America Top"] = true,
                ["Adidas Tank"] = true,
                ["Snowman Beanie"] = true,
                ["Kingsman Suit"] = true,
                ["Black Slacks"] = true,
                ["Luck Of The Irish Pants"] = true,
                ["Mad Hatter Top"] = true,
                ["Palm Tank"] = true,
                ["Football Cleats"] = true,
                ["Fault in Our Stars"] = true,
                ["Sunday Morning"] = true,
                ["Spring Style"] = true,
                ["Crown"] = true,
                ["Purple Glasses"] = true,
                ["Santa's Jacket"] = true,
                ["LA Spring"] = true,
                ["Crop Top"] = true,
                ["Blue Shutter Shades"] = true,
                ["Tomb Raider"] = true,
                ["Floral Windbreaker"] = true,
                ["Floral W/Denim"] = true,
                ["Pinstripe Fedora"] = true,
                ["Harley Quinn Shorts"] = true,
                ["Pink Striped Tank"] = true,
                ["Skeleton Top"] = true,
                ["Blue Jeans"] = true,
                ["Oh Christmas Tree"] = true,
                ["Ice Lightning"] = true,
                ["Zombie Girl"] = true,
                ["80s Hair"] = true,
                ["Black Tuxedo"] = true,
                ["Asuna Pants"] = true,
                ["Space Criminal Outfit"] = true,
                ["Candy Cane Stockings"] = true,
                ["Happy Spring"] = true,
                ["Qt Pumpkin"] = true,
                ["Tux Jacket w/Red Tie"] = true,
                ["Green Clover Tank"] = true,
                ["Fall Stripes"] = true,
                ["Gold Fedora"] = true,
                ["Holiday Swirls"] = true,
                ["Firefighter Jacket"] = true,
                ["Snowflake Sweater "] = true,
                ["Yellow Jeans"] = true,
                ["White Glasses"] = true,
                ["Sailor Suit"] = true,
                ["Clover Jacket"] = true,
                ["Floral Winter"] = true,
                ["None"] = true,
                ["Meowy Christmas"] = true,
                ["Paper Hat"] = true,
                ["Spring Top Hat"] = true,
                ["Mermaid"] = true,
                ["Little Penguins"] = true,
                ["Floral Top & Shorts"] = true,
                ["Shoulderless Sweater"] = true,
                ["Rudolph PJs"] = true,
                ["Tiara"] = true,
                ["Ash Hat"] = true,
                ["Galaxy Bikini"] = true,
                ["Black Jacket"] = true,
                ["Sora"] = true,
                ["Gray Camo Pants"] = true,
                ["Spooky Ghost"] = true,
                ["Disco Top"] = true,
                ["Rainbow Shades"] = true,
                ["Blue Striped Hoodie"] = true,
                ["Hawaiian Shirt"] = true,
                ["Red T-Shirt"] = true,
                ["Gingerbread Man"] = true,
                ["Blue & Bowtie"] = true,
                ["Brrrr"] = true,
                ["Doge PJ's"] = true,
                ["Striped Cardigan"] = true,
                ["Cozy Flannel"] = true,
                ["Kawaii Pajamas"] = true,
                ["Holiday Spirit"] = true,
                ["Classy Autumn"] = true,
                ["Team Cottontail"] = true,
                ["Pimp My Halloween"] = true,
                ["Yellow Spring Kicks"] = true,
                ["Space Criminal Top"] = true,
                ["Floral High-Low"] = true,
                ["Deadpool Top"] = true,
                ["Spring Denim"] = true,
                ["Skater Hat"] = true,
                ["Tropical One Piece"] = true,
                ["Shamrock Shorts"] = true,
                ["Best Gift Ever"] = true,
                ["Elsa's Dress"] = true,
                ["Chibi Penguin"] = true,
                ["Tacky Snowman"] = true,
                ["Grey Swim Trunks"] = true,
                ["Black Jacket & Gloves"] = true,
                ["Cheerleader"] = true,
                ["It's A Lie"] = true,
                ["Spring Hat"] = true,
                ["Pink Adidas Hoodie"] = true,
                ["Pink Waves"] = true,
                ["Happy Pawlidays"] = true,
                ["Smooth"] = true,
                ["Wonder Woman Skirt"] = true,
                ["Christmas Ball Gown"] = true,
                ["Orange Trunks"] = true,
                ["Ash Outfit"] = true,
                ["DC Hat"] = true,
                ["Chef Hat"] = true,
                ["Classy Patty"] = true,
                ["Tacky Sweater"] = true,
                ["Shark Attack"] = true,
                ["Elf Top"] = true,
                ["Snowflake Hoodie"] = true,
                ["Polar Express"] = true,
                ["Shamrockin Look"] = true,
                ["Jacket O' Lantern"] = true,
                ["Antlers"] = true,
                ["Tree Trunk"] = true,
                ["Floral Crown"] = true,
                ["Sweats"] = true,
                ["Save the Penguins!"] = true,
                ["Sleek Sunglasses"] = true,
                ["Retro Blue Blouse"] = true,
                ["Gold Chain"] = true,
                ["Not Santa"] = true,
                ["Camo Nike Shirt"] = true,
                ["Hat of Gifts"] = true,
                ["Punk (Sham)Rock"] = true,
                ["Pastel Tux Top"] = true,
                ["Chaun Man"] = true,
                ["Santa Sloth"] = true,
                ["Zombie Shirt"] = true,
                ["Pink One-Shoulder Top"] = true,
                ["Snoopy PJs"] = true,
                ["Shorts &  LA Tank Top"] = true,
                ["Tracer"] = true,
                ["Dead Bride"] = true,
                ["Santa Chic"] = true,
                ["Red Glasses"] = true,
                ["Black Shorts"] = true,
                ["Fuzzy Reindeer"] = true,
                ["Pure Awesome"] = true,
                ["Frankenstein Top"] = true,
                ["Pastel Winter Pink"] = true,
                ["Police Uniform"] = true,
                ["Blue Striped Tank"] = true,
                ["Basic Winter"] = true,
                ["Chibi Bunny"] = true,
                ["Nike Camo Tee"] = true,
                ["Eggcited For Bed"] = true,
                ["Kingsman"] = true,
                ["Bandana"] = true,
                ["Spring Fling Dress"] = true,
                ["Zebra Rainbow Shirt"] = true,
                ["Faded Jeans"] = true,
                ["Anna's Dress Top"] = true,
                ["Bun"] = true,
                ["Distressed Jeans"] = true,
                ["Scrubs"] = true,
                ["Tracer Top"] = true,
                ["Girly Mario"] = true,
                ["Classy Spring Dress"] = true,
                ["Superman"] = true,
                ["Lush"] = true,
                ["Galaxy Striped Tank"] = true,
                ["Double Gold Bangles"] = true,
                ["Peter Pan Hat"] = true,
                ["Yellow Shutter Shades"] = true,
                ["Gold Wrist Watch"] = true,
                ["Pennywise"] = true,
                ["Punk"] = true,
                ["Llama Wreath"] = true,
                ["Pointy"] = true,
                ["Spring Fling Tux Top"] = true,
                ["Bailleybug"] = true,
                ["Floral Tank"] = true,
                ["Fall PJs"] = true,
                ["Witch"] = true,
                ["Take No Chances"] = true,
                ["One With Nature"] = true,
                ["Red Flannel"] = true,
                ["Ghostly"] = true,
                ["Rugged"] = true,
                ["Green Polo"] = true,
                ["Anna's Dress"] = true,
                ["Blue Hawaiian Shirt"] = true,
                ["Disco Outfit"] = true,
                ["Netflix Sweats"] = true,
                ["Ugly Cat Sweater"] = true,
                ["Galaxy Leggings"] = true,
                ["Winter Sky Coat"] = true,
                ["Tribal Maxi Dress"] = true,
                ["Navy Blue Polo"] = true,
                ["Santa's Outfit"] = true,
                ["Grey Baseball Tee"] = true,
                ["Blue Shirt & Tie"] = true,
                ["Santa Hat"] = true,
                ["Spring Sweater"] = true,
                ["Shamrock Tee"] = true,
                ["Mad Hatter Outfit"] = true,
                ["Skeleton Tee"] = true,
                ["Camo Jacket"] = true,
                ["Winter Wonderland Sweater"] = true,
                ["Cargo Shorts & Shoes"] = true,
                ["Striped Clover Tank"] = true,
                ["So Eggcited"] = true,
                ["Plaid Luck"] = true,
                ["Black Hoodie"] = true,
                ["Eggy Easter Vest"] = true,
                ["Kawaii Christmas Kitty"] = true,
                ["Wonder Woman Tank"] = true,
                ["Moose Sweater"] = true,
                ["Tropical Bikini"] = true,
                ["Slick"] = true,
                ["School Jacket"] = true,
                ["Pastel Jacket"] = true,
                ["Hawaiian Dreams"] = true,
                ["Winter Camo Coat"] = true,
                ["Wonder Woman Top"] = true,
                ["Luigi Pants"] = true,
                ["Fall Suit Jacket"] = true,
                ["Shiro Skirt"] = true,
                ["Green Striped Hoodie"] = true,
                ["Mermaid Swimsuit"] = true,
                ["Murica"] = true,
                ["Pumpkin Head"] = true,
                ["Pumpkin Shorts"] = true,
                ["Red Maxi Dress"] = true,
                ["Hairspray"] = true,
                ["Pastel Winter Violet"] = true,
                ["Winter Wolf"] = true,
                ["Goth"] = true,
                ["Cargo Shorts"] = true,
                ["Mass Effect Hoodie"] = true,
                ["Dark Jeans w/Belt"] = true,
                ["Winter Business"] = true,
                ["Basic Rudolph"] = true,
                ["Aztec Winter Jacket"] = true,
                ["Simple Sweater"] = true,
                ["Galaxy Workout"] = true,
                ["Casual Pastel"] = true,
                ["Blue T-Shirt"] = true,
                ["Pixel PJs"] = true,
                ["Grey & Pink Button Up"] = true,
                ["Classy Rainbow Shirt"] = true,
                ["Skeleton Pants"] = true,
                ["Black Cardigan "] = true,
                ["Cyan Hoodie"] = true,
                ["Rainbow Bikini Bottom"] = true,
                ["Polar Bear Queen"] = true,
                ["Skirt Rudolph"] = true,
                ["Rabbit Feet"] = true,
                ["Link Pants"] = true,
                ["Joker Suit"] = true,
                ["Irish Gent"] = true,
                ["One Cool Chick"] = true,
                ["Roblox Hoodie"] = true,
                ["Candy Cane Cutie"] = true,
                ["Sweet Autumn"] = true,
                ["ShamWow"] = true,
                ["Kitty Ears"] = true,
                ["Pigtails"] = true,
                ["Floral leggings"] = true,
                ["Snowflake Beanie"] = true,
                ["Ugg It's Cold"] = true,
                ["Wild"] = true,
                ["Pink Jacket"] = true,
                ["Holiday Leggings"] = true,
                ["Shorts & Skull Top"] = true,
                ["Purple Sporty Shirt"] = true,
                ["Shorts & Tank Top"] = true,
                ["Princess Peach Top"] = true,
                ["Diamond Jean Shorts"] = true,
                ["Scarlet Short Dress"] = true,
                ["Pastel Swegg"] = true,
                ["Patty's Day PJ's"] = true,
                ["Superman Top"] = true,
                ["Backwards Cap"] = true,
                ["Edgy Spring"] = true,
                ["Punk Pumpkin"] = true,
                ["Lace With Pink Shorts"] = true,
                ["Shamrock Shirt & Tie"] = true,
                ["Braided"] = true,
                ["Santa Dress"] = true,
                ["Vintage Swimsuit"] = true,
                ["Kirito Outfit"] = true,
                ["Red Backpack"] = true,
                ["Classy Halloween"] = true,
                ["Aviators"] = true,
                ["Sharp"] = true,
                ["Mad Hatter Hat"] = true,
                ["Green Shutter Shades"] = true,
                ["Cute but Cold"] = true,
                ["Princess Peach Dress"] = true,
                ["Kawaii Ghost"] = true,
                ["Polar PJ TOP"] = true,
                ["Wavy"] = true,
                ["Tinted Aviators"] = true,
                ["Black One Piece"] = true,
                ["White Tuxedo"] = true,
                ["Khakis & Kicks"] = true,
                ["Orange Jacket"] = true,
                ["Blue Trunks"] = true,
                ["Elf Gown"] = true,
                ["Sloth Rudolph"] = true,
                ["Reindeerp"] = true,
                ["Classy Christmas Top"] = true,
                ["Orange Sweater"] = true,
                ["Clipped"] = true,
                ["Holiday Night Out"] = true,
                ["Clover Leggings"] = true,
                ["Wonder Woman"] = true,
                ["Clover Hoodie"] = true,
                ["Winter Dreams"] = true,
                ["Peter Pan Top"] = true,
                ["Black Joggers"] = true,
                ["Rainbow PJ's"] = true,
                ["Christmas Spirit"] = true,
                ["Asuna Top"] = true,
                ["Black Clover Trunks"] = true,
                ["Reverse Clover Jacket"] = true,
                ["Lantern Hoodie"] = true,
                ["Patty's Day Business"] = true,
                ["Banded Top Hat"] = true,
                ["One With The Egg"] = true,
                ["Stylish Sunglasses"] = true,
                ["Holiday Robes"] = true,
                ["Polka Dot"] = true,
                ["Gold Jacket"] = true,
                ["Tinker Bell"] = true,
                ["Halloween Outfit"] = true,
                ["Rainbow Bikini Top"] = true,
                ["80's Pop Star"] = true,
                ["Galaxy Dress"] = true,
                ["Easy Breezy"] = true,
                ["Peter Pants"] = true,
                ["Simple and Sweet"] = true,
                ["Mistletoe Santa"] = true,
                ["Mario Outfit"] = true,
                ["Pink Reindeer Sweater"] = true,
                ["2Spooky4You"] = true,
                ["High Waist Cheetah"] = true,
                ["Tree Top"] = true,
                ["Cold and Dead Inside"] = true,
                ["Firefighter Pants"] = true,
                ["Peter Hipstertail"] = true,
                ["Winter Wonderland "] = true,
                ["Mustache Top & Shorts"] = true,
                ["Gingerbread Man Top"] = true,
                ["Shorts And Cardigan"] = true,
                ["Black Open Jacket"] = true,
                ["Football Jersey"] = true,
                ["High Waist Shorts "] = true,
                ["North Crest Coat"] = true,
                ["Shaggy"] = true,
                ["Fur-lined Jacket"] = true,
                ["Yellow Striped Tank"] = true,
                ["Galaxy Tank Outfit"] = true,
                ["Link Top"] = true,
                ["MasterChaun"] = true,
                ["Turquoise One Piece"] = true,
                ["Mario Top"] = true,
                ["Tuxedo"] = true,
                ["Mr. Wonderland"] = true,
                ["Black Jeans"] = true,
                ["Frankenstein"] = true,
                ["Leaf Top"] = true,
                ["Messy"] = true,
                ["Pastel Winter Blue"] = true,
                ["Reindeer Cardigan"] = true,
                ["Captain America"] = true,
                ["Bloody Hoodie"] = true,
                ["Spring PJ's"] = true,
                ["Luigi Top"] = true,
                ["Easter Swegg"] = true,
                ["Vans T-Shirt"] = true,
                ["Plaid Bunny PJ's"] = true,
                ["Fuzzy Blue Jacket"] = true,
                ["Ripped Pants"] = true,
                ["Pink Shutter Shades"] = true,
                ["Men's Tank"] = true,
                ["Men's Striped Tank"] = true,
                ["Leprechaun Hat"] = true,
                ["Blue Spring Kicks"] = true,
                ["Summer Business"] = true,
                ["Red Adidas Hoodie"] = true,
                ["Sora Pants"] = true,
                ["Aztec Swimsuit"] = true,
                ["Autumn Leaves"] = true,
                ["Brown Winter Coat"] = true,
                ["Ponytail"] = true,
                ["Uniform"] = true,
                ["Harley Quinn Top"] = true,
                ["Striped Shirt w/Sweater"] = true,
                ["Headphones"] = true,
                ["Disco Hair"] = true,
                ["Fall Jacket"] = true,
                ["Easter PJ Set"] = true,
                ["Red Collar"] = true,
                ["Nike Galaxy"] = true,
                ["Green Sweater Vest"] = true,
                ["Muscle Shirt"] = true,
                ["Blue & Grey Jacket"] = true,
                ["Reverse Clover Hoodie"] = true,
                ["Clover Tank"] = true,
                ["Black Glasses"] = true
            },
            ["CurrentOutfit"] = {
                ["CharacterDesc"] = "",
                ["SkinColor"] = "Reddish brown",
                ["CustomShirtID"] = "",
                ["Face"] = "http://www.roblox.com/asset/?id=13038247",
                ["CharacterName"] = "........",
                ["Shirt"] = "Red T-Shirt",
                ["CharacterAge"] = 0,
                ["Pants"] = "Khakis & Kicks",
                ["Extras"] = "None",
                ["Hat"] = "None",
                ["HairColor"] = "Really red",
                ["Gender"] = "Male",
                ["Right Arm"] = "None",
                ["Left Arm"] = "Gold Wrist Watch",
                ["Glasses"] = "None",
                ["CustomPantsID"] = "",
                ["Hair"] = "Smooth"
            }
        }
    }
}

game:GetService("ReplicatedStorage").Relays.DataManagement.PrimaryDataSave:InvokeServer(unpack(args))
